// <auto-generated />
using System;
using Fitness_Tracker.Infrastucture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Tracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250309063449_AddedIsDeletePropertyToEntities")]
    partial class AddedIsDeletePropertyToEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Athlete identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User Identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Athletes", t =>
                        {
                            t.HasComment("Athlete table");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserID = "8d477d39-83ed-4155-81de-a65dd76c2627"
                        },
                        new
                        {
                            Id = 2,
                            UserID = "99612cd5-354c-42b9-966b-779154d8055c"
                        });
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Exercise identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Exercise description, can be of maximum 1000 characters");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Exercise name, can be of maximum 50 characters");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Boolean property for delete.");

                    b.Property<int>("TargetMuscleGroup")
                        .HasColumnType("int")
                        .HasComment("Exercise muscle group");

                    b.HasKey("Id");

                    b.ToTable("Exercises", t =>
                        {
                            t.HasComment("Exercise");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Squats",
                            ImageUrl = "https://images.unsplash.com/photo-1612957824445-f0c090ff1af0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8c3F1YXRzfGVufDB8fDB8fHww",
                            IsDeleted = false,
                            TargetMuscleGroup = 7
                        },
                        new
                        {
                            Id = 2,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Bicep Curls",
                            ImageUrl = "",
                            IsDeleted = false,
                            TargetMuscleGroup = 4
                        },
                        new
                        {
                            Id = 3,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Tricep Extentions",
                            ImageUrl = "",
                            IsDeleted = false,
                            TargetMuscleGroup = 5
                        },
                        new
                        {
                            Id = 4,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Cable Row",
                            ImageUrl = "",
                            IsDeleted = false,
                            TargetMuscleGroup = 2
                        },
                        new
                        {
                            Id = 5,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Bench Press",
                            ImageUrl = "",
                            IsDeleted = false,
                            TargetMuscleGroup = 1
                        },
                        new
                        {
                            Id = 6,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Shoulder Press",
                            ImageUrl = "",
                            IsDeleted = false,
                            TargetMuscleGroup = 3
                        },
                        new
                        {
                            Id = 7,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Crunches",
                            ImageUrl = "",
                            IsDeleted = false,
                            TargetMuscleGroup = 1
                        },
                        new
                        {
                            Id = 8,
                            ExerciseDescription = "Some random text for testing.",
                            ExerciseName = "Dynamic stretching",
                            ImageUrl = "",
                            IsDeleted = false,
                            TargetMuscleGroup = 0
                        });
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Intensity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Intensity identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvarageTimePerSet")
                        .HasColumnType("int")
                        .HasComment("Avarage Number of seconds per one set.");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasComment("Identifier of current exercise.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Boolean property for delete.");

                    b.Property<int>("LiftedWeight")
                        .HasColumnType("int")
                        .HasComment("The avarage weight with witch the exercise was performed.");

                    b.Property<int>("Reps")
                        .HasColumnType("int")
                        .HasComment("Number of repetitions the exercise was performed.");

                    b.Property<int>("Sets")
                        .HasColumnType("int")
                        .HasComment("Number of sets performed.");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int")
                        .HasComment("Workout identifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Intensities", t =>
                        {
                            t.HasComment("Exercise intensity for current workout.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvarageTimePerSet = 45,
                            ExerciseId = 1,
                            IsDeleted = false,
                            LiftedWeight = 50,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvarageTimePerSet = 45,
                            ExerciseId = 2,
                            IsDeleted = false,
                            LiftedWeight = 10,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 3,
                            AvarageTimePerSet = 45,
                            ExerciseId = 3,
                            IsDeleted = false,
                            LiftedWeight = 10,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 4,
                            AvarageTimePerSet = 45,
                            ExerciseId = 4,
                            IsDeleted = false,
                            LiftedWeight = 30,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 5,
                            AvarageTimePerSet = 45,
                            ExerciseId = 5,
                            IsDeleted = false,
                            LiftedWeight = 40,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 6,
                            AvarageTimePerSet = 45,
                            ExerciseId = 6,
                            IsDeleted = false,
                            LiftedWeight = 20,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 7,
                            AvarageTimePerSet = 45,
                            ExerciseId = 7,
                            IsDeleted = false,
                            LiftedWeight = 30,
                            Reps = 10,
                            Sets = 3,
                            WorkoutId = 1
                        });
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Workout identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("int")
                        .HasComment("User Identifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Boolean property for delete.");

                    b.Property<string>("WorkoutType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Workout type.");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Workouts", t =>
                        {
                            t.HasComment("Workout table");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AthleteId = 2,
                            IsDeleted = false,
                            WorkoutType = "Full body."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8d477d39-83ed-4155-81de-a65dd76c2627",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20efacc3-3ab4-487f-afa5-a094c62bb11a",
                            Email = "admin@fitnesstracker.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FITNESSTRACKER.COM",
                            NormalizedUserName = "ADMIN@FITNESSTRACKER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEASHF2cfqXMFxe1DzFsoXvJnsMQEh7HdrUXRDkstnlSwuaGWBLsC5Ezr/XUBfgu37A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8aeeddf4-9888-4224-8757-b2c43bac9b67",
                            TwoFactorEnabled = false,
                            UserName = "admin@fitnesstracker.com"
                        },
                        new
                        {
                            Id = "99612cd5-354c-42b9-966b-779154d8055c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9256276d-9f57-459d-a4f5-59cdb4238984",
                            Email = "testOne@fitnesstracker.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTONE@FITNESSTRACKER.COM",
                            NormalizedUserName = "TESTONE@FITNESSTRACKER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN4izp4y58QjxK/oHd5WoyayGbxSI8GQzNmZPFGQyFfaJeG2FhuQoQQZz0hByXKoyg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f874522e-9df9-4311-b500-f3076f7a2129",
                            TwoFactorEnabled = false,
                            UserName = "testOne@fitnesstracker.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Athlete", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Intensity", b =>
                {
                    b.HasOne("Fitness_Tracker.Infrastructure.Data.Models.Exercise", "Exercise")
                        .WithMany("Intensities")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fitness_Tracker.Infrastructure.Data.Models.Workout", "Workout")
                        .WithMany("Intensities")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.HasOne("Fitness_Tracker.Infrastructure.Data.Models.Athlete", "Athlete")
                        .WithMany("Workouts")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Athlete", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Navigation("Intensities");
                });

            modelBuilder.Entity("Fitness_Tracker.Infrastructure.Data.Models.Workout", b =>
                {
                    b.Navigation("Intensities");
                });
#pragma warning restore 612, 618
        }
    }
}
